spring.application.name=smart-campus


server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=500MB

spring.datasource.url=jdbc:mysql://localhost:3306/paf_uni_smart_class_group_project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anuradhawork123@gmail.com
spring.mail.password=umae tfzt zkli wjow
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jwt.secret=ql0E2C9sTHEQ8Kxxggce+GP88iITTgj19aF1YW8E09Jk/zlz+0AqUD1rbfC6N3U2TrdeEI2y/CgwLYWghtpWZw==

spring.cookie.secure=false
spring.cookie.same-site=Lax